#!/usr/bin/env ruby

# based on https://apple.stackexchange.com/a/162354

require 'fileutils'

if ARGV.empty?
  $stderr.write("usage: #{File.basename($PROGRAM_NAME)} file(s)\n       move file(s) to Trash\n")
  exit(1)
end

files = []
ARGV.each do |arg|
  if File.exist?(arg)
    p = File.absolute_path(arg).gsub('"', '\"').gsub('\\', '\\\\')
    files << "the POSIX file \"#{p}\""
  else
    $stderr.write("#{File.basename($PROGRAM_NAME)}: #{arg}: No such file or directory\n")
  end
end

if files.any?
  cmd = ['osascript', '-e', "tell app \"Finder\" to move {#{files.join(', ')}} to trash"]
  # puts cmd.join(' ')
  r = system(*cmd, out: File::NULL)
  exit(r && files.size == ARGV.size ? 0 : 1)
end
